const Images = {
    logo : require('../Assets/Images/icLoginLogo3x.png'),
    logoSmall : require('../Assets/Images/icLoginLogo2x.png'),
    logoImage: require('../Assets/Images/icLoginLogo.png'),
    googleLogo: require('../Assets/Images/googlePlus.png'),
    facebookLogo: require('../Assets/Images/facebook.png'),
    party : require('../Assets/Images/partyImg.jpg'),
    heartFilled: require('../Assets/Images/icSavedActive.png'),
    heartEmpty: require('../Assets/Images/icSavedDeactive.png'),
    cheers: require('../Assets/Images/cheers.png'),
    musicIcon: require('../Assets/Images/music-player.png'),
    trekIcon: require('../Assets/Images/hiking.png'),
    calendar: require('../Assets/Images/calendar.png'),
    logoIcon: require('../Assets/Images/icMyeventsDeselect.png'),
    person1: require('../Assets/Images/person1.jpeg'),
    person2: require('../Assets/Images/person2.jpeg'),
    person3: require('../Assets/Images/person3.jpeg'),
    run: require('../Assets/Images/run.png'),
    cancelImage: require('../Assets/Images/icCross.png'),
    thumbnail: require('../Assets/Images/thumbnail.png'),
    maleDefault: require('../Assets/Images/maleImageDefault.jpg'),
    recommend: require('../Assets/Images/recommend.jpg'),
    venue: require('../Assets/Images/venue.jpg'),
    maleImage: require('../Assets/Images/maleImage.jpeg'),
    cancel: require('../Assets/Images/icCancel.png'),
    info: require('../Assets/Images/icInfo.png'),
    smallInfo: require('../Assets/Images/icNewinfo.png'),
    listArrow: require('../Assets/Images/icAccountNextArrow.png'),
    launchScreen: require('../Assets/Images/launch_screen.png'),
}

export default Images;