const strings = {
    hello: "Hello",
    helloStrangers: "Hello Stranger!",
    welcomeTo: "Welcome to Group Set Go.",
    whereSharingExperiences: "Sharing experiences is made easy",
    newToGroupSetGo: "New to Group set go?",
    youCanAlsoLoginWith: "You can also login with",
    skipLogin: "SKIP LOGIN",
    welcomeBack: 'Welcome Back!',
    signInToContinue: 'Sign in to continue...',
    forgotyourPassword: 'Forgot your password?',
    dontWorry: "Don't worry. We can help.",
    resetPassword: 'Reset Password.',
    keepItStrong: 'Keep it super strong.',
    participantList: 'Participant List',
    recentSearches: 'RECENT SEARCHES',
    priceDetails: 'Price Details',
    totalBudget: 'Total Budget',
    finalBudget: 'Final Budget',
    amountRefunded: 'Amount Refunded',
    raiseIncedent: 'RAISE INCIDENT',
    rateReview: 'RATE & REVIEW',
    eventDate: 'Event Date',
    lastDateToLeave: 'Last Date to Leave Event',
    costBreakdown: 'Cost Breakdown',
    totalCost: 'Total Cost',
    agreeToTerms: 'I agree to the Terms and Conditions',
    alertText: 'Please note that you cannot create or join events without logging in.',
    inappropriate: 'Are you sure you want to flag this inappropriate?',
    awesome: 'Awesome!',
    created: 'Lets get your account created.',
    step1: 'STEP 1 OF 5',
    name: 'So...Whats in the name?',
    nameDescription: 'Forget what Shakespeare said. Tell us what to call you, so there are no more formalities.',
    next: 'Next',
    step2: 'STEP 2 OF 5',
    email: 'Your email address?',
    emailDescription: 'We hate spams as much as you do. We promise not to send any unwanted emails.',
    step3: 'STEP 3 OF 5',
    birth: 'Your birthday?',
    birthDescription: 'Some of our events have age restrictions for participants. Don’t worry, we won’t share this information on any other platform.',
    step4: 'STEP 4 OF 5',
    gender: 'Your gender?',
    genderDescription: 'Some of our events are gender specific. sLet us know which gender you belong to.',
    step5: 'STEP 5 OF 5',
    pass: 'Create Password',
    passDescription: 'Password must include atleast one symbol and must be more than 6 characters.',
    submit: 'Submit',
    firstName: 'Enter First Name',
    lastName: 'Enter Last Name',
    emailPlaceholder: 'Enter email address',
    passPlaceholder: 'Password',
    passConfirm: 'Confirm Password',
    male: 'Male',
    female: 'Female',
    search: 'Search event, users',
    sort: 'Sort',
    filter: 'Filter',
    recommended: 'Recommended',
    allEvents: 'All Events',
    explore: 'EXPLORE',
    saved: 'SAVED',
    myEvents: 'MY EVENTS',
    chat: 'CHAT',
    perPerson: 'per person',
    join: "Join",
    saveIcon: 'Save',
    savedIcon: 'Saved',
    share: 'Share',
    chatIcon: 'Chat',
    going: 'Leave',
    perPersonSmall: 'per person',
    cancel: 'Cancel By: ',
    details: 'Details',
    eventId: 'Event ID',
    verified: 'Verified Users Only',
    ageGroup: 'Age Group',
    genderMix: 'Gender Mix',
    reviews: 'reviews',
    maleMix: 'Min. Male:',
    femaleMix: 'Min. Female:',
    budget: 'Total Budget: ',
    venue: 'Venue Location',
    organizer: 'Organizer',
    leaveEvent: 'Leave Event',
    participants: 'Participants',
    waitlist: 'Waitlist',
    reviews: 'Reviews',
    settleAcc: 'settle account',
    description: 'Description',
    response: 'Your response has been submitted!',
    enterData: 'Please enter your reason!',
    min: 'min',
    max: 'max',
    letsStartWithEvent: "Let's start with the event.",
    justAMinute: 'Just take a minute! Why join alone when you can bring your special ones with you!',
    doYouWantAccompany: 'Do you want to accompany with someone?',
    howManyGuests: 'How many guests you are inviting?',
    youCanBring: 'You can bring upto 4 guests.',
    LeaveEvent: 'Are you sure you want to LEAVE the event? May not receive any Refund of Payments made',
    Name: "Please enter a valid name!",
    Email: 'Please enter valid email!',
    passwordMatch: "Please enter valid matching passwords!",
    Email_Password: 'Please enter a valid response!',
    responseEmail: 'Please check your email to reset password!',
    RaiseIncedent: 'Are you sure you want to raise a report regading this event?',
    UnderWork: "This is under construction at the moment!",
    review: 'Review',
    confirm: 'CONFIRM',
    raiseIncidentHeading: 'Raise Incident',
    cancelIt: 'Cancel',
    Yes: 'Yes',
    No: 'No',
    RateReview: 'Rate & Review',
    SKIP: 'SKIP',
    rateStep1: 'STEP 1/3',
    rateStep2: 'STEP 2/3',
    rateStep3: 'STEP 3/3',
    rateHost: 'Do you want to rate your host?',
    tellUs: 'Tell us about your experience.',
    pleaseTellUs: 'Please tell us about your experience',
    joinAgain: 'Would you like to attend this event again?',
    rateVenue: 'Do you want to rate the Venue?',
    rate_review: 'Your rating & review has been posted successfully.',
    goingPeople: 'Going',
    createEvent: 'Create Event',
    save: 'SAVE',
    saveModal: 'Your data has been saved!',
    createEventStep1: 'STEP 1/4: EVENT DETAILS',
    fillAll: "Please enter all of the details!",
    createEventStep2: 'STEP 2/4: ADDITIONAL DETAILS',
    createEventStep3: 'STEP 3/4: PARTICIPANTS DETAILS',
    createEventStep4: 'STEP 4/4: BUDGET DETAILS',
    addPhoto: 'ADD PHOTO',
    addPhotoTextString: "Photos help more engagement from the participants.",
    category: 'CATEGORY',
    select: 'Select',
    sortBy: 'sort by',
    distance: 'distance',
    onlyBudget: 'budget',
    perctFill: 'percentage fill',
    openSlots: 'open slots',
    filters: 'filters',
    reset: 'reset',
    info1: "Date Range: Selecting a date range would only display the events that have the event date in the range selected.",
    info2: "Per Person Cost: Provides the ability to see Only Free Events, Only Paid Events or Both. You can even select the per person cost range according to your budget",
    info3: "Min Available Slots: If you are bringing company, using this option, you can filter the events to only those that can accommodate your group.",
    info4: "% Fill: Gives an indication of how close the event is to meeting the MINIMUM participant count.",
    info5: 'Family Friendly Only: If you have underage kids in the group, you can filter to "Family Friendly Only" events that will not have age restrictions.',
    dateRange: 'date range',
    perPersonCost: 'per person cost',
    freeEvent: 'free events',
    paidEvent: 'paid events',
    selectCategories: 'Select Categories',
    done: 'Done',
    familyFriendly: "Family Friendly",
    eventType: 'EVENT TYPE',
    private: 'Private',
    public: 'Public',
    text1: ' Family friendly events do not have age restrictions for participants and safer for all age groups.',
    text2: 'In Public events, anyone meeting criteria (age, gender & verification status) can join. In Private events, event owner can  ad/ remove participants & tehse events are not discoverable without direct URL / Auth code / Invite email',
    availableSlot: 'available slots',
    percent: 'percent filled',
    eventCategory: 'event category',
    familyFriends: 'family friends only',
    apply: 'apply filters',
    totalParticipants: 'Total Participants',
    ageRestriction: 'Age Restriction',
    age: 'Age',
    genderMix: 'Specify Gender Mix',
    resetAll: 'Do you want to Reset All filters ?',
    resetall: 'Reset All',
    myAccount: 'my account',
    account: 'account',
    help: 'help',
    inviteFrnd: 'invite friend',
    logout: 'Logout',
    noSaved: 'No saved events found!',
    shareCost: 'Share Cost',
    publish: 'Publish',
    publishedEvent1: 'Your Private event with',
    publishedEvent2: 'is now successfully created.',
    fixedCost: 'Fixed Total Cost',
    fixedPerson: 'Fixed Per Person Cost',
    budgetBreak: 'Budget Breakdown',
}

export default strings;