const strings = {
    hello: "Hello",
    helloStrangers: "Hello Stranger!",
    welcomeTo: "Welcome to Group Set Go.",
    whereSharingExperiences: "Sharing experiences is made easy",
    newToGroupSetGo: "New to Group set go?",
    youCanAlsoLoginWith: "You can also login with",
    skipLogin: "SKIP LOGIN",
    welcomeBack: 'Welcome Back!',
    signInToContinue: 'Sign in to continue...',
    forgotyourPassword: 'Forgot your password?',
    dontWorry: "Don't worry. We can help.",
    resetPassword: 'Reset Password.',
    keepItStrong: 'Keep it super strong.' ,
    participantList: 'Participant List',
    recentSearches : 'RECENT SEARCHES',
    priceDetails: 'Price Details',
    totalBudget: 'Total Budget',
    finalBudget: 'Final Budget',
    amountRefunded: 'Amount Refunded',
    raiseIncedent: 'RAISE INCEDENT',
    rateReview: 'RATE & REVIEW',
    eventDate: 'Event Date',
    lastDateToLeave: 'Last Date to Leave Event',
    costBreakdown: 'Cost Breakdown',
    totalCost: 'Total Cost',
    agreeToTerms: 'I agree to the Terms and Conditions'
}

export default strings;