export default CATEGORIES = [
    {
        name:'Adventure',
        selected:false
    },
    {
        name:'Art',
        selected:false
    },
    {
        name:'Causes',
        selected:false
    },
    {
        name:'Dance',
        selected:false
    },
    {
        name:'Drinks',
        selected:false
    },
    {
        name:'Films',
        selected:false
    },
    {
        name:'Fitness',
        selected:false
    },
    {
        name:'Food',
        selected:false
    },
    {
        name:'Music Concert',
        selected:false
    },
    {
        name:'Networking',
        selected:false
    },
    {
        name:'Outdoor',
        selected:false
    },
    {
        name:'Party',
        selected:false
    },
    {
        name:'Sports & Games',
        selected:false
    },
    {
        name:'Travel',
        selected:false
    },
    {
        name:'Others',
        selected:false
    },
]