import {Images} from './Constants'

export default DATA = [
    {
        serialNo: 1,
        source: Images.res1,
        time: 'TODAY,JUL 14 • 7 PM',
        heading: 'Dance Floor Table @ Omnia',
        place: 'Caesars Palace, Las Vegas',
        money: '$600- $800',
        going: 10,
        icon: Images.cheers,
        profile: Images.maleImage,
        hashtag: '#Dancefloortable',
        reviewRating: '4.5',
        location: '3570 S Las Vegas Blvd, Las Vegas, NV 89109',
        cancelDate: '06/30/2018',
        hearted: false,
        
        // image: Images.res1,
        // iconImage: Images.cheers,
        // profile: Images.maleImage,
        // time: 'TODAY,JUL 14 • 7 PM',
        // heading: 'Dance Floor Table @ Omnia',
        // hashtag: '#Dancefloortable',
        // reviewRating: '4.5',
        // going: '8',
        // location: '3570 S Las Vegas Blvd, Las Vegas, NV 89109',
        // money: '$600- $800',
        // cancelDate: '06/30/2018'
    },
    {
        serialNo: 2,
        source: Images.res2,
        time: 'SAT,JUL 19 • 3 PM',
        heading: 'Tea Time Party @ Resolutions',
        place: 'Coffee Palace, Las Vegas',
        money: '$800- $1000',
        going: 7,
        icon: Images.musicIcon,
        profile: Images.maleImage,
        hashtag: '#Dancefloortable',
        reviewRating: '4.5',
        location: '3570 S Las Vegas Blvd, Las Vegas, NV 89109',
        cancelDate: '06/30/2018',
         hearted: false,
    },
    {
        serialNo: 3,
        source: Images.res1,
        time: 'TODAY,JUL 14 • 7 PM',
        heading: 'Dance Floor Table @ Omnia',
        place: 'Caesars Palace, Las Vegas',
        money: '$600- $800',
        going: 10,
        icon: Images.cheers,
        profile: Images.maleImage,
        hashtag: '#Dancefloortable',
        reviewRating: '4.5',
        location: '3570 S Las Vegas Blvd, Las Vegas, NV 89109',
        cancelDate: '06/30/2018',
         hearted: false,
    },
    {
        serialNo: 4,
        source: Images.res2,
        time: 'SAT,JUL 19 • 3 PM',
        heading: 'Tea Time Party @ Resolutions',
        place: 'Coffee Palace, Las Vegas',
        money: '$800- $1000',
        going: 7,
        icon: Images.musicIcon,
        profile: Images.maleImage,
        hashtag: '#Dancefloortable',
        reviewRating: '4.5',
        location: '3570 S Las Vegas Blvd, Las Vegas, NV 89109',
        cancelDate: '06/30/2018',
         hearted: false,
    },
    {
        serialNo: 5,
        source: Images.travel,
        time: 'MON,JUL 16 • 7 AM',
        heading: 'Backpacking & Hiking at the Mountains',
        place: 'Lake Havasu',
        money: '$200 - 250',
        going: 4,
        icon: Images.trekIcon,
        profile: Images.maleImage,
        hashtag: '#Dancefloortable',
        reviewRating: '4.5',
        location: '3570 S Las Vegas Blvd, Las Vegas, NV 89109',
        cancelDate: '06/30/2018',
         hearted: false,
    },
    {
        serialNo: 6,
        source: Images.music,
        time: 'WED, Jul 18 • 7 pm ',
        heading: 'Chicago Music Festival',
        place: 'Randolph St, Chicago',
        money: '$45- $90',
        going: 35,
        icon: Images.musicIcon,
        profile: Images.maleImage,
        hashtag: '#Dancefloortable',
        reviewRating: '4.5',
        location: '3570 S Las Vegas Blvd, Las Vegas, NV 89109',
        cancelDate: '06/30/2018',
         hearted: false,
    },
    {
        serialNo: 7,
        source: Images.travel,
        time: 'MON,JUL 16 • 7 AM',
        heading: 'Backpacking & Hiking at the Mountains',
        place: 'Lake Havasu',
        money: '$200 - 250',
        going: 4,
        icon: Images.trekIcon,
        profile: Images.maleImage,
        hashtag: '#Dancefloortable',
        reviewRating: '4.5',
        location: '3570 S Las Vegas Blvd, Las Vegas, NV 89109',
        cancelDate: '06/30/2018',
         hearted: false,
    },
    {
        serialNo: 8,
        source: Images.music,
        time: 'WED, Jul 18 • 7 pm ',
        heading: 'Chicago Music Festival',
        place: 'Randolph St, Chicago',
        money: '$45- $90',
        going: 35,
        icon: Images.musicIcon,
        profile: Images.maleImage,
        hashtag: '#Dancefloortable',
        reviewRating: '4.5',
        location: '3570 S Las Vegas Blvd, Las Vegas, NV 89109',
        cancelDate: '06/30/2018',
         hearted: false,
    }
]